CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                VARCHAR(255)                            NOT NULL,
    email                   VARCHAR(255)                            NOT NULL,
    password                VARCHAR(255)                            NOT NULL,
    enabled                 BOOLEAN                                 NOT NULL,
    verification_code       VARCHAR(255),
    verification_expiration TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

INSERT INTO users (username, email, password, enabled)
VALUES (
        'berk',
        'berksengul9a@gmail.com',
        '$2b$12$YuPwpWKVkdVElR9oiTRP7u9XwWHJGnmkakOTEdHcfgCo9EswurolS',
        true
       );