CREATE TABLE document
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    upload_date  date,
    content      OID,
    content_type VARCHAR(255),
    status       VARCHAR(255),
    CONSTRAINT pk_document PRIMARY KEY (id)
);