CREATE TABLE pii_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    start        INTEGER                                 NOT NULL,
    "end"        INTEGER                                 NOT NULL,
    document_id  BIGINT                                  NOT NULL,
    is_high_risk BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_piientity PRIMARY KEY (id)
);

ALTER TABLE pii_entity
    ADD CONSTRAINT FK_PIIENTITY_ON_DOCUMENT FOREIGN KEY (document_id) REFERENCES document (id);